# Generated by Django 4.1.3 on 2023-04-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('main_image', models.ImageField(null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
