# Generated by Django 4.1.3 on 2023-05-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='likeonpost',
            table='like_on_post',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='post_image',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
