# Generated by Django 4.1.3 on 2023-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usercontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='image',
            field=models.ImageField(null=True, upload_to='user_content'),
        ),
    ]
