# Generated by Django 4.1.3 on 2023-05-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userimage_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usercontent',
            table='user_content',
        ),
        migrations.AlterModelTable(
            name='userimage',
            table='user_image',
        ),
    ]
